sudo: false
language: python
python:
    - "2.7"
    - "3.6"
addons:
    apt:
        packages:
        - ghostscript
install:
    - env | sort
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION graphviz mock multipledispatch notebook nbconvert numpy=1.12.1 pandas pillow pip reportlab scikit-image
    - source activate test-environment
    - pip install arrow behave coverage coveralls custom_inherit nose-exclude pypng six xmldiff
    - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
    - mkdir ffmpeg
    - tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg
    - export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
    - ffmpeg -version
    - python setup.py develop
script:
    - coverage run --source toyplot -m behave --no-logcapture
    - coverage combine --append docs/.coverage
    - coverage report
    - python backend-report.py
after_script:
    - coveralls
